### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by alem0lars** [jeaye/color_coded#109] opened 2016-01-24 08:29 UTC
The command `cmake .` fails with the following output:

```
Determining if the pthread_create exist failed with the following output:
Change Dir: /etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_98321/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_98321.dir/build.make CMakeFiles/cmTC_98321.dir/build
gmake[1]: Entering directory '/etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_98321.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_98321.dir/CheckSymbolExists.c.o   -c /etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_98321
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_98321.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_98321.dir/CheckSymbolExists.c.o  -o cmTC_98321 -rdynamic 
CMakeFiles/cmTC_98321.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_98321.dir/build.make:97: recipe for target 'cmTC_98321' failed
gmake[1]: *** [cmTC_98321] Error 1
gmake[1]: Leaving directory '/etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_98321/fast' failed
gmake: *** [cmTC_98321/fast] Error 2

File /etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_667a0/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_667a0.dir/build.make CMakeFiles/cmTC_667a0.dir/build
gmake[1]: Entering directory '/etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_667a0.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_667a0.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_667a0
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_667a0.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_667a0.dir/CheckFunctionExists.c.o  -o cmTC_667a0 -rdynamic -lpthreads 
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_667a0.dir/build.make:97: recipe for target 'cmTC_667a0' failed
gmake[1]: *** [cmTC_667a0] Error 1
gmake[1]: Leaving directory '/etc/vim/bundle/color_coded/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_667a0/fast' failed
gmake: *** [cmTC_667a0/fast] Error 2
```

Apparently it fails to find `pthreads`.

**Comment by UnrealQuester** [comment] 2016-01-24 09:02
It looks like the test for pthread_create itself fails. Knowing cmake, this may also be a problem completly unrelated to that. Can we get a little more info about your system?
What distro are you using?
Did you install all the packages in the README?

Also, you might want to try to remove color_coded, clone it again and then do an out of source build in a subdirectory.
```bash
mkdir build && cd build
cmake ..
```

**Comment by alem0lars** [comment] 2016-01-24 17:59
* I use the GNU/Linux distro: `Gentoo`
* I've installed all the packages listed in the `README.md` file, in particular:
  * `GCC` version `4.9.3`
  * `CMake` version `3.3.1-r1`

When I try to run:

```
mkdir build && cd build
cmake ..
```

gives a different error: 

```
-- Found 64bit system
-- Updating submodules
-- Looking for Lua
-- Found Lua
--   Lua include /usr/include
--   Lua lib /usr/lib64/liblua.so;/usr/lib64/libm.so
-- Locating trusted Clang/LLVM 3.6.0
-- Found clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
-- Clang/LLVM 3.6.0 already extracted
-- Generating sources
CMake Error at cmake/generate_sources.cmake:2 (execute_process):
  execute_process called with no value for WORKING_DIRECTORY.
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)


-- Checking for luajit
-- Configuring incomplete, errors occurred!
See also "/etc/vim/bundle/color_coded/CMakeFiles/CMakeOutput.log".
```

**Comment by UnrealQuester** [comment] 2016-01-24 20:16
I happen to have the same setup and am unable to reproduce the issue. What shell are you calling cmake from? Does `echo $PWD` work?

The cmake error tells me that $ENV{PWD} is not set, which seems strange.

**Comment by alem0lars** [comment] 2016-01-24 20:22
Did u create the build directory and did `cmake..`?

**Comment by UnrealQuester** [comment] 2016-01-24 20:30
Yes.

**Comment by alem0lars** [comment] 2016-01-25 09:37
@UnrealQuester `echo $PWD` prints the current working directory..

[![asciicast](https://asciinema.org/a/3vlpzeh8u2qovr9no5w8fia81.png)](https://asciinema.org/a/3vlpzeh8u2qovr9no5w8fia81)

**Comment by UnrealQuester** [comment] 2016-01-25 14:27
Thank you for the video. I can reproduce the problem now. Looks like `sudo` messes with the cmake environment. I am not sure if the issue can be fixed on our part, bur for a temporary workaround you can try two things:

1. Use `sudo su` to become root and finish the installation as root
2. Build the project in a directory where your user has write access and move the directory to `/etc/vim/bundle` afterwards.

**Comment by alem0lars** [comment] 2016-01-25 14:40
I can confirm that if I **dont't** use `sudo`, the commands `cmake ..`, `make`, `make install` work correctly.

**Comment by jeaye** [comment] 2016-01-25 14:43
@UnrealQuester Thanks for keeping up with this; you're the man.

I've just watched the video as well, and there are a couple of serious issues. @alem0lars, firstly: **building third party software as root puts you at a terrible risk of running arbitrary commands as root**. Don't do it. Secondly, using `sudo` does not give you a full root environment; it keeps your existing environment and allows you to run a command. Take a moment to look into `sudo` vs `sudo -i` and `su` versus `su -` to understand the ramifications.

**Comment by neverchanje** [comment] 2016-02-05 06:11
@UnrealQuester's solution works for me.

**Closed** 2016-03-30 21:24 UTC
