### ISSUE TITLE
[question] NeoVIM support

### ISSUE THREAD

**Issue by silvioprog** [jeaye/color_coded#185] opened 2019-09-21 16:04 UTC
Hi.

Is there any plans to support NeoVIM?

Thank you!

**Comment by jeaye** [comment] 2019-09-21 17:43
This is a duplicate of #89, so I'll close it and you can read through the progress made there. As far as updates newer than that, I'm not currently working on color_coded beyond maintenance, so changes like this are up to the community; I'd be happy to review PRs for clang updates and nvim support.

**Closed by jeaye** 2019-09-21 17:43 UTC
