### ISSUE TITLE
Include opencv header file, then occur errors

### ISSUE THREAD

**Issue by myme5261314** [jeaye/color_coded#93] opened 2015-11-19 08:34 UTC
I've made out a simple toy project to reproduce this issue.
The project is [here](https://github.com/myme5261314/toy-issue63-color_coded.git)
Here's the `CCerror` info.

![image](https://cloud.githubusercontent.com/assets/1814831/11265907/3a99fd0a-8edb-11e5-8f19-1cfa163d62c7.png)

![image](https://cloud.githubusercontent.com/assets/1814831/11265894/2acebaf0-8edb-11e5-8899-8a77bcdc57d3.png)

-------
PS: The opencv library was installed through apt-get under Ubuntu 14.04.3_x64.

**Comment by jeaye** [comment] 2015-11-19 08:37
That github link is invalid. In order to compile with opencv, do you need other compilation flags which should be provided in your `.color_coded` file?

**Comment by myme5261314** [comment] 2015-11-19 08:40
@jeaye the link has been fixed now.

**Comment by jeaye** [comment] 2015-11-19 08:46
Ok, you have some non-standard makefile setup, but looks like it's doing a lot more than just what you have in your `.color_coded`. Please make sure that there are no compilation flags in being passed to your normal build that aren't in your `.color_coded`. Any defines, include path changes, etc.

Please to try compile your project, using clang, with the flags provided in your makefile. Once you're certain that your code compiles with clang, try printing out variables like CXX_FLAGS during the compilation process. Make sure everything in those flags makes it into your `.color_coded`.

**Comment by myme5261314** [comment] 2015-11-19 09:22
@jeaye I've remove the makefile and write my simple one to test as you said. The `CCerror` still output the same error messages. I think that might be the issue of *clang*.

Running this command will compile the code to executable `toy` which will run successfully
> g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
> g++ -Wall -DDEBUG -g -rdynamic -std=c++11 -Iinclude  src/main.cpp -o toy

But using clang will give me the error.
> Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix

> clang -Wall -DDEBUG -g -rdynamic -std=c++11 -Iinclude  src/main.cpp -o toy
> In file included from src/main.cpp:9:
In file included from /usr/include/opencv2/opencv.hpp:47:
In file included from /usr/include/opencv2/core/core.hpp:58:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/cstddef:51:11: error: 
      no member named 'max_align_t' in the global namespace
  using ::max_align_t;
           ~~^
1 error generated.
make: *** [toy] 错误 1

------
I've pushed the commit to [my repo](https://github.com/myme5261314/toy-issue63-color_coded), you could check it again to see if there won't be issue caused by Makefile.

**Comment by jeaye** [comment] 2015-11-19 09:28
If your project doesn't compile with clang, then we've certainly ruled out color_coded as the issue here. I recommend trying to add `-stdlib=libc++` to your clang command line (color_coded already does this) as it may help. Other than that, when you're able to fix compilation of your project with clang, you'll almost certainly be able to use color_coded as well.

**Comment by myme5261314** [comment] 2015-11-20 08:48
@jeaye  To be honest, I don't know what you mean to get `color_coded` to work properly. 
1.  So the `color_coded` use `clang` as its internal compiler?
2.  What if my project prefers to use g++ as its compiler?
3.  Do I need to use different compile flags for clang to the one for g++?
4.  So, when the project can be compiled and linked properly through makefile, and then the `.color_coded` file was generated by [Ycm Generator](https://github.com/rdnetto/YCM-Generator), need I modify its content to get the `color_coded` works properly?
5.  When I use `Ycm Generator` to generator project config file`.ycm_extra_conf.py` and `.color_coded`, they seems to have the same compilation flags, but the **code completion** works fine while the **`:CCerror`** shows error. Is it because of clang stuff?
6. Could my issue be reproduced? [new repo](https://github.com/myme5261314/toy-issue-color_coded).

I think my toy project was simple enough to demonstrate what issue I'm facing now. The settings below all have the issue like this image. But these command all works fine and the compiled executable runs fines.
![Issue](https://cloud.githubusercontent.com/assets/1814831/11265894/2acebaf0-8edb-11e5-8899-8a77bcdc57d3.png)
> main.cpp
``` C++
#include <opencv2/opencv.hpp>
using namespace cv;
int main() {
    Mat r = Mat::zeros(100, 100, CV_8UC1);
    while(waitKey(1) == -1) {
        cv::imshow("r", r);
    }
    return 0;
}
```
-----

> makefile1
``` makefile
all: 
	g++ main.cpp -lopencv_core -lopencv_highgui -o toy
```
> .color_coded
```
-x
c++
```
-----
>makefile2
``` makefile
all: main.o
	clang main.cpp -lopencv_core -lopencv_highgui -o toy -lstdc++
```
> .color_coded
```
-x
c
```
-----
> makefile3
``` makefile
all: main.o
        clang++ main.cpp -lopencv_core -lopencv_highgui -o toy
```
> .color_coded
```
-x
c++
```

**Comment by jeaye** [comment] 2015-11-20 09:39
On Fri, Nov 20, 2015 at 12:48:34AM -0800, Peng Liu wrote:
>    [1]@jeaye To be honest, I don't know what you mean to get color_coded to
>    work properly.
>    1. So the color_coded use clang as its internal compiler?
>    2. What if my project prefers to use g++ as its compiler?
>    3. Do I need to use different compile flags for clang to the one for g++?

If your project has been proven to be compilable with clang 3.6, it
should work with color_coded (assuming a proper .color_coded). Last time
you tried, I believe, your code didn't compile properly with clang.

>    4. So, when the project can be compiled and linked properly through
>    makefile, and then the .color_coded file was generated by [2]Ycm
>    Generator, need I modify its content to get the color_coded works
>    properly?

If the makefile is using clang++ for the CXX and everything goes through
well, and you generate a corresponding .color_coded (with YCM Generator
or otherwise), you should be all set.

>    5. When I use Ycm Generator to generator project config
>    file.ycm_extra_conf.py and .color_coded, they seems to have the same
>    compilation flags, but the code completion works fine while the :CCerror
>    shows error. Is it because of clang stuff?

That's curious. The only real difference is that YCM is using clang 3.7
and color_coded is using clang 3.6. Since you're only using C++11, this
doesn't change anything (3.7 has more C++17 support).

>    6. Could my issue be reproduced? [3]new repo.

I haven't yet tried, since, last I heard, your code didn't compile
properly with clang. Does it now?

**Comment by myme5261314** [comment] 2015-11-20 09:56
@jeaye 
Yes, the three makefiles I listed above compile properly and their output executable program works fine. The related `.color_coded` file was generated by `YCM-Generator`.
And the curious situation indeed exists. You could see that `imshow()` wasn't properly highlighted, but when I use the same configuration, YCM could help me complete the code.
See image below.

> ![image](https://cloud.githubusercontent.com/assets/1814831/11296900/e84e5962-8faf-11e5-84df-97ffe600492b.png)

-----
> ![2015-11-20 17 49 16](https://cloud.githubusercontent.com/assets/1814831/11296883/c3316962-8faf-11e5-9a1c-4075e928a7fc.png)

**Comment by UnrealQuester** [comment] 2015-11-20 17:26
I tested the repo you linked and was unable to reproduce the issue on my machine. imshow gets highlighted and CCerror does not show any errors. So clang doesn't seem to be the issue here. As the .color_coded file only contains `-x c++`, which are in the default flags, you could delete it and it should still work.
Can you paste the complete output of `:CCerror` here?

**Comment by myme5261314** [comment] 2015-11-23 01:52
@UnrealQuester So, it seems to be my problem since you are unable to reproduce this issue.
The output of `:CCerror` was below.
> ![CCerror](https://cloud.githubusercontent.com/assets/1814831/11265894/2acebaf0-8edb-11e5-8899-8a77bcdc57d3.png)

What about your opencv library, do you compiled it by yourself or install the pre-built package? Which OS were you on?

Is your opencv headers in the path of `/usr/include/opencv2`?

**Comment by UnrealQuester** [comment] 2015-11-23 19:51
I'm running gentoo with opencv 2.4.9. The headers are indeed located at `/usr/include/opencv2`. What version of opencv are you using?

**Comment by myme5261314** [comment] 2015-11-24 01:24
@UnrealQuester  I'm using opencv 2.4.8 which is installed via apt-get under Ubuntu 14.04.

**Comment by UnrealQuester** [comment] 2015-11-25 18:36
Will see if I can reproduce that in a ubuntu vm.

**Comment by UnrealQuester** [comment] 2015-11-27 19:38
I could reproduce the error.
Try rebuilding color_coded with a custom clang version. Try installing `clang-3.6 llvm-3.6 llvm-3.6-dev` and then do `cmake -DCUSTOM_CLANG=1 -DLLVM_ROOT_PATH=/usr/lib/llvm-3.6 . && make && make install` in your color_coded folder.

**Comment by myme5261314** [comment] 2015-11-29 15:44
@UnrealQuester As you said, following the compilation procedure about Ubuntu in README.md will cause my reported issue, and using the procedure you supplied will eliminate the issue.

@jeaye I think the README.md should be updated about the compilation procedure under Ubuntu, right?

Note that this is another laptop rather than my working PC in the company, so the issue should be confirmed. Using the procedure described in README.md will cause my report issue.

> ![image](https://cloud.githubusercontent.com/assets/1814831/11457995/df675156-96f2-11e5-8d59-e0a899386370.png)

**Comment by jeaye** [comment] 2015-11-30 04:41
@myme5261314 The technique you used to build with the system clang is not officially supported. The real question is why it works with your clang and not the one color_coded pulls down. Will you please tell me your system clang version? color_coded is using clang 3.6.0.

@UnrealQuester Thanks for putting time into this; you're the man. Let me know if you have any ideas as to why the system clang works.

**Comment by UnrealQuester** [comment] 2015-11-30 18:47
@jeaye Seems like libclang does not include the same header paths as the actual clang binary. See http://clang-developers.42468.n3.nabble.com/Default-header-search-paths-not-included-when-compiling-from-libclang-td4036193.html and https://github.com/Valloric/YouCompleteMe/issues/303
I think YCM avoids this by adding the paths manually. The ubuntu clang version is also 3.6.0 with some additional patches.

**Comment by jeaye** [comment] 2015-12-01 02:16
@UnrealQuester color_coded also adds some paths manually. See https://github.com/jeaye/color_coded/blob/master/include/conf/defaults.hpp#L48. On your ubuntu machine, will you share the output of

```bash
$ echo | clang -v -E -x c++ -
```

and also

```bash
$ echo | clang -v -E -std=libc++ -x c++ -
```

Thanks for looking into this; if it's path related, we should be able to solve it by improving color_coded's defaults. If it's still an issue on more obscure platforms, we can direct people to just adjust their .color_coded files with the output of those clang/gcc commands.

**Comment by myme5261314** [comment] 2015-12-01 02:40
Here's mine.
``` shell
$ echo | clang -v -E -x c++ -
Ubuntu clang version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.2.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.2.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-3.6/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -E -disable-free -disable-llvm-verifier -main-file-name - -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.24 -v -dwarf-column-info -resource-dir /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include -internal-externc-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/deeplearn -ferror-limit 19 -fmessage-length 80 -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 3.6.0 based upon LLVM 3.6.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward
 /usr/local/include
 /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 320 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

-----
``` shell
$ echo | clang -v -E -std=libc++ -x c++ -
Ubuntu clang version 3.6.0-2ubuntu1~trusty1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/5.2.1
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.2.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-3.6/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -E -disable-free -disable-llvm-verifier -main-file-name - -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.24 -v -dwarf-column-info -resource-dir /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include -internal-externc-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=libc++ -fdeprecated-macro -fdebug-compilation-dir /home/deeplearn -ferror-limit 19 -fmessage-length 80 -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
error: invalid value 'libc++' in '-std=libc++'
```

**Comment by jeaye** [comment] 2015-12-01 02:48
@myme5261314 Thanks! Will you please try the following:

1) Rebuild color_coded normally, without system clang
2) Verify the problem exists again
3) Add this to your `.color_coded`

```text
-I/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9
-I/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/x86_64-linux-gnu/c++/4.9
-I/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward
-I/usr/local/include
-I/usr/lib/llvm-3.6/bin/../lib/clang/3.6.0/include
-I/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/include
-I/usr/include/x86_64-linux-gnu
-I/usr/include
```

4) Let me know if the problem still exists

**Comment by UnrealQuester** [comment] 2015-12-01 12:53
I tried that in my ubuntu test environment. The only required include was
```
-isystem
/usr/include/c++/4.9/
```
opencv 2.4.8 relies on <ext/atomicity.h>, which is a gcc only extension. Looks like the ubuntu clang version has a patch to include this as well. opencv 2.4.9 no longer needs this, which explains why it worked on my machine.

**Comment by jeaye** [comment] 2016-04-27 05:56
As pointed out, there's a local fix for this and an upstream one. Thanks again, @UnrealQuester.

**Closed** 2016-04-27 05:55 UTC
Labels: reproducible
