### ISSUE TITLE
C++ file "No such highlight group name"

### ISSUE THREAD

**Issue by tony** [jeaye/color_coded#115] opened 2016-03-18 20:50 UTC
I wonder what could be causing this issue..

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>                                                                                                                                                       
"~/study/c++/project/src/viewport.cpp" 3252L
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: TypeRef
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: VarDecl
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: VarDecl
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: VarDecl
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: VarDecl
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: VarDecl
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: Variable
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: StructDecl
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: TypeRef
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
line    2:
E28: No such highlight group name: FieldDecl
Error detected while processing function color_coded#moved[7]..color_coded#add_match:
```

```
❯ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 15 2016 16:27:18)
Included patches: 1-1556
Compiled by root@head-amd64-default-job-10
Huge version with GTK2 GUI.  Features included (+) or not (-):
```

This is on cd38aa8 with downloaded clang and https://github.com/tony/color_coded/tree/llvm-cmake-revamp (with clang/llvm 3.8).

**Comment by UnrealQuester** [comment] 2016-03-19 10:30
I am asuming this has nothing to do with the changes in your fork. Can you try to create a minimal vimrc so we can reproduce this issue?

**Comment by vimeitor** [comment] 2017-04-23 23:03
I get this issue if I open vim without any file and then open any file from it. If I open vim with a file (vim file.c), then I have no issues.

**Comment by jeaye** [comment] 2017-04-23 23:53
I don't think color_coded likes being lazy loaded very much; I haven't investigated it deeply, since color_coded does almost nothing until it's actually needed. It just says "when I'm needed (i.e. you open a buffer of this type), let me know." If color_coded is showing up in your load time profiling as a culprit, I'd be surprised, but much more willing to dive deeper.

**Comment by vimeitor** [comment] 2017-04-23 23:57
Thank you for the fast reply. Yeah, it's completely fine :) I think lazy loading a plugin is by itself a bit of a hack, so no worries. I found this plugin a couple of days ago and I wish I had found it earlier. Really amazing. Thank you for your work :)

**Comment by jeaye** [comment] 2017-04-23 23:58
Cheers! Let us know if you have any issues.

**Comment by jeaye** [comment] 2017-05-16 00:20
Closing, since I haven't seen any activity here or any more reports of this. Feel free to re-open if this shows up again.

**Closed by jeaye** 2017-05-16 00:20 UTC
